#!/bin/bash

SUBDOMAIN=$(grep -Po '.{1,}(?=.domien-gillard.sb.uclllabs.be)' <<< "$1")

PART=$(cut -d. -f2 <<< "$1")

SUB=$(cut -d. -f1 <<< "$1")

ZONE=$(cut -d. -f2- <<< "$1")

echo "$ZONE"

FIND='^'"$SUB"'\s'

echo "$FIND"

EXISTS=$(grep -P "$FIND" /etc/bind/zones/db."$ZONE" | wc -l)

echo "$EXISTS"

if [ "$EXISTS" -gt 0 ]; then

	mkdir /var/www/html/"$SUBDOMAIN"
	touch /var/www/html/"$SUBDOMAIN"/index.html

	echo "<html><head><title>$SUBDOMAIN</title></head><body><p>welcome $SUBDOMAIN</p></body></html>" >> /var/www/html/"$SUBDOMAIN"/index.html;

	sed "s/changethis/$SUBDOMAIN/g" /etc/apache2/sites-available/.vhost_template.conf > /etc/apache2/sites-available/"$SUBDOMAIN".conf

	a2ensite "$SUBDOMAIN".conf
	systemctl reload apache2

else

	echo "Something went wrong"
	exit 1

fi
